[project]
name = 'droplinked-contract'
description = 'droplinked is a commerce infrastructure network operating as a decentralized inventory management and sales tracking system for digital and physical goods.'
authors = ['Erfan Yeganegi <yeganegierfan@gmail.com>']
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.droplinked-contract]
path = 'contracts/droplinked-contract.clar'
clarity_version = 2
epoch = 2.1

[contracts.droplinked-gateway]
path = 'contracts/droplinked-gateway.clar'
clarity_version = 2
epoch = 2.1

[contracts.sft-trait]
path = 'contracts/sft-trait.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
