[project]
name = 'droplinked-stacks-contract'
description = 'droplinked is a commerce infrastructure network operating as a decentralized inventory management and sales tracking system for digital and physical goods.'
authors = ["Erfan Yeganegi <yeganegierfan@gmail.com>"]
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.droplinked-sft-trait]
path = 'contracts/droplinked-sft-trait.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
