[project]
name = 'droplinked-stacks-contract'
description = 'droplinked is a commerce infrastructure network operating as a decentralized inventory management and sales tracking system for digital and physical goods.'
authors = ['Erfan Yeganegi <yeganegierfan@gmail.com>']
telemetry = true
cache_dir = '.cache'
requirements = []

[contracts.droplinked-base]
path = 'contracts/droplinked-base.clar'
clarity_version = 2
epoch = 2.4

[contracts.droplinked-operator]
path = 'contracts/droplinked-operator.clar'
clarity_version = 2
epoch = 2.4

[contracts.droplinked-sft-trait]
path = 'contracts/droplinked-sft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.droplinked-token]
path = 'contracts/droplinked-token.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
